p8105_hw2_qc2336
================
Qiran Chen
2023-09-26

## Problem 1

``` r
pol_month = read_csv(file = "./data/pols-month.csv")|>
  janitor::clean_names()|>
  separate(mon, into = c("year", "month","day"), convert = TRUE) |>
  mutate(year=as.integer(year),
  month=month.abb[as.numeric(month)],
  day=as.integer(day))|>
  mutate(president=recode(prez_dem, `1`="dem",`0`="gop"))|>
  select(-prez_dem,-prez_gop, -day)
```

    ## Rows: 822 Columns: 9
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl  (8): prez_gop, gov_gop, sen_gop, rep_gop, prez_dem, gov_dem, sen_dem, r...
    ## date (1): mon
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
pol_month
```

    ## # A tibble: 822 × 9
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president
    ##    <int> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>    
    ##  1  1947 Jan        23      51     253      23      45     198 dem      
    ##  2  1947 Feb        23      51     253      23      45     198 dem      
    ##  3  1947 Mar        23      51     253      23      45     198 dem      
    ##  4  1947 Apr        23      51     253      23      45     198 dem      
    ##  5  1947 May        23      51     253      23      45     198 dem      
    ##  6  1947 Jun        23      51     253      23      45     198 dem      
    ##  7  1947 Jul        23      51     253      23      45     198 dem      
    ##  8  1947 Aug        23      51     253      23      45     198 dem      
    ##  9  1947 Sep        23      51     253      23      45     198 dem      
    ## 10  1947 Oct        23      51     253      23      45     198 dem      
    ## # ℹ 812 more rows

``` r
snp = read_csv(file = "./data/snp.csv")|>
  janitor::clean_names()|>
  separate(date,into = c("month","day","year"),convert=TRUE)|>
  mutate(month=month.abb[as.integer(month)],
         year=as.numeric(year),
        year=ifelse(year<=20,year+2000,year+1900))|>
  arrange(year,month)|>
  select(year,month,close,-c("day"))
```

    ## Rows: 787 Columns: 2
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): date
    ## dbl (1): close
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
snp
```

    ## # A tibble: 787 × 3
    ##     year month close
    ##    <dbl> <chr> <dbl>
    ##  1  1950 Apr    18.0
    ##  2  1950 Aug    18.4
    ##  3  1950 Dec    20.4
    ##  4  1950 Feb    17.2
    ##  5  1950 Jan    17.0
    ##  6  1950 Jul    17.8
    ##  7  1950 Jun    17.7
    ##  8  1950 Mar    17.3
    ##  9  1950 May    18.8
    ## 10  1950 Nov    19.5
    ## # ℹ 777 more rows

``` r
unemployment=read_csv(file = "./data/unemployment.csv")|>
  pivot_longer(Jan:Dec,
               names_to = 'month',
               values_to = 'per_unemploy')|>
  rename(year=Year)
```

    ## Rows: 68 Columns: 13
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## dbl (13): Year, Jan, Feb, Mar, Apr, May, Jun, Jul, Aug, Sep, Oct, Nov, Dec
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
unemployment
```

    ## # A tibble: 816 × 3
    ##     year month per_unemploy
    ##    <dbl> <chr>        <dbl>
    ##  1  1948 Jan            3.4
    ##  2  1948 Feb            3.8
    ##  3  1948 Mar            4  
    ##  4  1948 Apr            3.9
    ##  5  1948 May            3.5
    ##  6  1948 Jun            3.6
    ##  7  1948 Jul            3.6
    ##  8  1948 Aug            3.9
    ##  9  1948 Sep            3.8
    ## 10  1948 Oct            3.7
    ## # ℹ 806 more rows

``` r
pol_snp=left_join(pol_month,snp,by=c("year","month"))

pol_snp_unemp=left_join(pol_snp,unemployment,by=c("year","month"))

pol_snp_unemp
```

    ## # A tibble: 822 × 11
    ##     year month gov_gop sen_gop rep_gop gov_dem sen_dem rep_dem president close
    ##    <dbl> <chr>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl>   <dbl> <chr>     <dbl>
    ##  1  1947 Jan        23      51     253      23      45     198 dem          NA
    ##  2  1947 Feb        23      51     253      23      45     198 dem          NA
    ##  3  1947 Mar        23      51     253      23      45     198 dem          NA
    ##  4  1947 Apr        23      51     253      23      45     198 dem          NA
    ##  5  1947 May        23      51     253      23      45     198 dem          NA
    ##  6  1947 Jun        23      51     253      23      45     198 dem          NA
    ##  7  1947 Jul        23      51     253      23      45     198 dem          NA
    ##  8  1947 Aug        23      51     253      23      45     198 dem          NA
    ##  9  1947 Sep        23      51     253      23      45     198 dem          NA
    ## 10  1947 Oct        23      51     253      23      45     198 dem          NA
    ## # ℹ 812 more rows
    ## # ℹ 1 more variable: per_unemploy <dbl>

> > The pol_month dtata set contains the number of republican and
> > democrates in senate, governor and presidential positions in
> > 1947-2015, it has 822 observations and 9 variables including whether
> > the president is dem or rep on the date. The snp data shows the
> > closing value of stock in 1950-2015, it has 787 observatins and 10
> > variables, the most important variable is the closing value. And the
> > umemployment data shows the unempolyment rate in 1948-2015, the
> > variable per_unemploy shows the unemploymet percentage of each date.
> > The pol_snp_unemp data frame has 822 observation of 11 variables
> > with the variables in the aforementioned dataframes combined from
> > year 1947-2015.

## Problem 2

    ## # A tibble: 584 × 15
    ##    dumpster month  year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 May    2014 2014-05-16 00:00:00        4.31                 18
    ##  2        2 May    2014 2014-05-16 00:00:00        2.74                 13
    ##  3        3 May    2014 2014-05-16 00:00:00        3.45                 15
    ##  4        4 May    2014 2014-05-17 00:00:00        3.1                  15
    ##  5        5 May    2014 2014-05-17 00:00:00        4.06                 18
    ##  6        6 May    2014 2014-05-20 00:00:00        2.71                 13
    ##  7        7 May    2014 2014-05-21 00:00:00        1.91                  8
    ##  8        8 May    2014 2014-05-28 00:00:00        3.7                  16
    ##  9        9 June   2014 2014-06-05 00:00:00        2.52                 14
    ## 10       10 June   2014 2014-06-11 00:00:00        3.76                 18
    ## # ℹ 574 more rows
    ## # ℹ 9 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, sports_balls <dbl>, homes_powered <dbl>, type <chr>

``` r
Pf_trashwheel = readxl::read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet="Professor Trash Wheel" ,range ="A2:L108")|>
  janitor::clean_names() |>
  drop_na(dumpster)|>
  mutate(type="Pf_trashwheel")

Pf_trashwheel
```

    ## # A tibble: 106 × 13
    ##    dumpster month     year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>    <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00        1.79                 15
    ##  2        2 January   2017 2017-01-30 00:00:00        1.58                 15
    ##  3        3 February  2017 2017-02-26 00:00:00        2.32                 18
    ##  4        4 February  2017 2017-02-26 00:00:00        3.72                 15
    ##  5        5 February  2017 2017-02-28 00:00:00        1.45                 15
    ##  6        6 March     2017 2017-03-30 00:00:00        1.71                 15
    ##  7        7 April     2017 2017-04-01 00:00:00        1.82                 15
    ##  8        8 April     2017 2017-04-20 00:00:00        2.37                 15
    ##  9        9 May       2017 2017-05-10 00:00:00        2.64                 15
    ## 10       10 May       2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 96 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, type <chr>

``` r
Gwynnda = readxl::read_excel("./data/202309 Trash Wheel Collection Data.xlsx", sheet="Gwynnda Trash Wheel" ,range ="A2:L157")|>
  janitor::clean_names() |>
  drop_na(dumpster)|>
  mutate(type="gwynnda")

Gwynnda
```

    ## # A tibble: 155 × 13
    ##    dumpster month   year date                weight_tons volume_cubic_yards
    ##       <dbl> <chr>  <dbl> <dttm>                    <dbl>              <dbl>
    ##  1        1 July    2021 2021-07-03 00:00:00        0.93                 15
    ##  2        2 July    2021 2021-07-07 00:00:00        2.26                 15
    ##  3        3 July    2021 2021-07-07 00:00:00        1.62                 15
    ##  4        4 July    2021 2021-07-16 00:00:00        1.76                 15
    ##  5        5 July    2021 2021-07-30 00:00:00        1.53                 15
    ##  6        6 August  2021 2021-08-11 00:00:00        2.06                 15
    ##  7        7 August  2021 2021-08-14 00:00:00        1.9                  15
    ##  8        8 August  2021 2021-08-16 00:00:00        2.16                 15
    ##  9        9 August  2021 2021-08-16 00:00:00        2.6                  15
    ## 10       10 August  2021 2021-08-17 00:00:00        3.21                 15
    ## # ℹ 145 more rows
    ## # ℹ 7 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, plastic_bags <dbl>, wrappers <dbl>,
    ## #   homes_powered <dbl>, type <chr>

``` r
trash_tidy = 
  bind_rows(Pf_trashwheel, Gwynnda, Mr_trashwheel) |>
  select(type,dumpster,everything())

trash_tidy
```

    ## # A tibble: 845 × 15
    ##    type  dumpster month  year date                weight_tons volume_cubic_yards
    ##    <chr>    <dbl> <chr> <dbl> <dttm>                    <dbl>              <dbl>
    ##  1 Pf_t…        1 Janu…  2017 2017-01-02 00:00:00        1.79                 15
    ##  2 Pf_t…        2 Janu…  2017 2017-01-30 00:00:00        1.58                 15
    ##  3 Pf_t…        3 Febr…  2017 2017-02-26 00:00:00        2.32                 18
    ##  4 Pf_t…        4 Febr…  2017 2017-02-26 00:00:00        3.72                 15
    ##  5 Pf_t…        5 Febr…  2017 2017-02-28 00:00:00        1.45                 15
    ##  6 Pf_t…        6 March  2017 2017-03-30 00:00:00        1.71                 15
    ##  7 Pf_t…        7 April  2017 2017-04-01 00:00:00        1.82                 15
    ##  8 Pf_t…        8 April  2017 2017-04-20 00:00:00        2.37                 15
    ##  9 Pf_t…        9 May    2017 2017-05-10 00:00:00        2.64                 15
    ## 10 Pf_t…       10 May    2017 2017-05-26 00:00:00        2.78                 15
    ## # ℹ 835 more rows
    ## # ℹ 8 more variables: plastic_bottles <dbl>, polystyrene <dbl>,
    ## #   cigarette_butts <dbl>, glass_bottles <dbl>, plastic_bags <dbl>,
    ## #   wrappers <dbl>, homes_powered <dbl>, sports_balls <dbl>

> > The three data has the relative similar variables, the key variables
> > are the weight tons of the trash collected and the homes powers. The
> > Mr. Trashwheel data set has 584 observation and 15 variable, Gwynnda
> > has 13 variable and 108 observations, Pr_trashwheel has 106
> > observations and 13 variables. The difference is on the kind of
> > trash collected, variables such as plastic bags are not measured in
> > the other datasets. The total trash collected by pf_trashwheel is
> > 216.26 and total for gwynnda is 451.65

## Problem 3

``` r
baseline = read_csv(file = "./data/data_mci/MCI_baseline.csv", skip=1)|>
  janitor::clean_names()|>
  mutate(sex=factor(sex,levels=c(0,1),labels=c("Female","Male")),
         apoe4=factor(apoe4,levels=c(0,1),labels=c("Non-carrier","Carrier")),
         age_at_onset=as.numeric(age_at_onset))|>
  drop_na(age_at_onset)
```

    ## Rows: 483 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (1): Age at onset
    ## dbl (5): ID, Current Age, Sex, Education, apoe4
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There was 1 warning in `mutate()`.
    ## ℹ In argument: `age_at_onset = as.numeric(age_at_onset)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion

``` r
baseline
```

    ## # A tibble: 97 × 6
    ##       id current_age sex    education apoe4       age_at_onset
    ##    <dbl>       <dbl> <fct>      <dbl> <fct>              <dbl>
    ##  1     3        62.5 Male          16 Carrier             66.8
    ##  2     5        66   Male          16 Non-carrier         68.7
    ##  3     7        66.5 Male          18 Non-carrier         74  
    ##  4    13        63.1 Male          12 Carrier             69  
    ##  5    14        58.4 Female        20 Non-carrier         66.2
    ##  6    18        67.8 Male          16 Non-carrier         69.8
    ##  7    22        67.3 Female        20 Carrier             74.6
    ##  8    26        64.8 Female        20 Carrier             71.1
    ##  9    30        66.3 Female        12 Non-carrier         73.1
    ## 10    39        68.3 Female        16 Carrier             70.2
    ## # ℹ 87 more rows

> > The data set has six variabled. Current age, age at onset, sex,
> > apoe4 gene, and id. In this data set, the important steps are to
> > change the binary data sex and apoe 4 into chracters. And change the
> > age of onset into numeric data so it can drop the missing value.

``` r
baseline|>
  count(sex, apoe4)
```

    ## # A tibble: 4 × 3
    ##   sex    apoe4           n
    ##   <fct>  <fct>       <int>
    ## 1 Female Non-carrier    16
    ## 2 Female Carrier        30
    ## 3 Male   Non-carrier    20
    ## 4 Male   Carrier        31

> > 483 people are recruited but only 97 developed mci. The mean
> > baseline age is 65.6113402 . 0.75 of the women are APOE4 carriers.

``` r
amyloid = read_csv(file = "./data/data_mci/mci_amyloid.csv",skip=1)|>
  janitor::clean_names()|>
  mutate(baseline=as.numeric(baseline),
         time_2=as.numeric(time_2),
         time_4=as.numeric(time_4),
         time_6=as.numeric(time_6),
         time_8=as.numeric(time_8))|>
  rename(id=study_id)
```

    ## Rows: 487 Columns: 6
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (5): Baseline, Time 2, Time 4, Time 6, Time 8
    ## dbl (1): Study ID
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

    ## Warning: There were 5 warnings in `mutate()`.
    ## The first warning was:
    ## ℹ In argument: `baseline = as.numeric(baseline)`.
    ## Caused by warning:
    ## ! NAs introduced by coercion
    ## ℹ Run `dplyr::last_dplyr_warnings()` to see the 4 remaining warnings.

``` r
amyloid
```

    ## # A tibble: 487 × 6
    ##       id baseline time_2 time_4 time_6 time_8
    ##    <dbl>    <dbl>  <dbl>  <dbl>  <dbl>  <dbl>
    ##  1     1    0.111 NA      0.109  0.105  0.107
    ##  2     2    0.107  0.109  0.109  0.106  0.107
    ##  3     3    0.106  0.109  0.106 NA      0.106
    ##  4     4    0.109  0.109  0.111  0.107  0.111
    ##  5     5    0.108  0.112  0.115  0.107  0.106
    ##  6     6    0.112  0.113  0.111  0.110  0.115
    ##  7     7    0.112 NA      0.104  0.112  0.112
    ##  8     8    0.110  0.109 NA      0.109  0.110
    ##  9     9    0.112  0.110  0.109 NA     NA    
    ## 10    10    0.112  0.112 NA     NA      0.110
    ## # ℹ 477 more rows

> > This data has six variable, id, baseline, time 2,4,6,8. It’s mostly
> > numerical but it shows it is character in data set. During the
> > tidying this is changed by using mutate. The study id is renamed as
> > id so it is easier for the table to merge.

``` r
base_amyloid<-left_join(baseline,amyloid,by="id")

write_csv(base_amyloid, 'base_amyloid.csv')

base_amyloid
```

    ## # A tibble: 97 × 11
    ##       id current_age sex    education apoe4  age_at_onset baseline time_2 time_4
    ##    <dbl>       <dbl> <fct>      <dbl> <fct>         <dbl>    <dbl>  <dbl>  <dbl>
    ##  1     3        62.5 Male          16 Carri…         66.8    0.106  0.109  0.106
    ##  2     5        66   Male          16 Non-c…         68.7    0.108  0.112  0.115
    ##  3     7        66.5 Male          18 Non-c…         74      0.112 NA      0.104
    ##  4    13        63.1 Male          12 Carri…         69      0.110  0.109  0.108
    ##  5    14        58.4 Female        20 Non-c…         66.2   NA     NA     NA    
    ##  6    18        67.8 Male          16 Non-c…         69.8    0.114  0.107  0.111
    ##  7    22        67.3 Female        20 Carri…         74.6    0.109 NA      0.108
    ##  8    26        64.8 Female        20 Carri…         71.1    0.105  0.110  0.106
    ##  9    30        66.3 Female        12 Non-c…         73.1    0.109  0.111  0.107
    ## 10    39        68.3 Female        16 Carri…         70.2    0.104 NA      0.104
    ## # ℹ 87 more rows
    ## # ℹ 2 more variables: time_6 <dbl>, time_8 <dbl>

> > Some participants are removed in the baseline dataset becomes they
> > never developed mci. When left joined the dataset has 97 observation
> > of subjects that developed mci during the study and their
> > longtitudinal data combined with data in baseline. It has 11
> > variables that is show in the two table.
